
export default {
  LOAD_STATS_SUCCESS            : 'LOAD_STATS_SUCCESS',
  LOAD_STAT_SUCCESS             : 'LOAD_STAT_SUCCESS',
  UPDATE_STAT_SUCCESS           : 'UPDATE_STAT_SUCCESS',
  CREATE_STAT_SUCCESS           : 'CREATE_STAT_SUCCESS',
  SAVE_STAT_ERROR               : 'SAVE_STAT_ERROR',
  LOAD_SETTINGS_SUCCESS         : 'LOAD_SETTINGS_SUCCESS',
  LOAD_SETTING_SUCCESS          : 'LOAD_SETTING_SUCCESS',
  UPDATE_SETTING_SUCCESS        : 'UPDATE_SETTING_SUCCES',
  LOGIN_USER_SUCCESS            : 'LOGIN_USER_SUCCESS',
  LOAD_FB_LOGIN_META_SUCCESS    : 'LOAD_FB_LOGIN_META_SUCCESS'
};
